# Generated by Django 2.2.14 on 2020-11-02 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePollMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('is_open', models.BooleanField(default=False, verbose_name='Is Open')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Vote Opened At')),
                ('opening_duration_minustes', models.PositiveSmallIntegerField(default=5, verbose_name='Vote Opening Duration Minustes')),
                ('batch_no', models.PositiveIntegerField(verbose_name='Batch No.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultiple_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultiple_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Live Poll Multiple',
                'verbose_name_plural': 'Live Poll Multiples',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivePollMultipleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('text', models.CharField(max_length=63)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultipleitem_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('live_poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multiple_items', to='live_poll_multiple.LivePollMultiple')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultipleitem_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Live Poll Multiple Item',
                'verbose_name_plural': 'Live Poll Multiple Items',
                'managed': True,
                'unique_together': {('text', 'live_poll')},
            },
        ),
        migrations.CreateModel(
            name='LivePollMultipleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('result', jsonfield.fields.JSONField(blank=True, null=True)),
                ('voting_date', models.DateField(blank=True, null=True, verbose_name='Voting Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultipleresult_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('live_poll', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='live_poll_multiple.LivePollMultipleItem')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultipleresult_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Live Poll Multiple Result',
                'verbose_name_plural': 'Live Poll Multiple Results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivePollMultipleItemVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('vote_option', models.PositiveSmallIntegerField(verbose_name='Vote Option')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultipleitemvote_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('live_poll_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multiple_item_votes', to='live_poll_multiple.LivePollMultipleItem')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultipleitemvote_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Poll Multiple Item Vote',
                'verbose_name_plural': 'Live Poll Multiple Item Votes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivePollMultipleProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultipleproxy_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('live_poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multiple_proxy_batches', to='live_poll_multiple.LivePollMultiple')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multiple_main_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_multiple_livepollmultipleproxy_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('proxy_users', models.ManyToManyField(related_name='multiple_proxy_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Poll Multiple Proxy',
                'verbose_name_plural': 'Live Poll Multiple Proxys',
                'managed': True,
                'unique_together': {('live_poll', 'main_user')},
            },
        ),
    ]
