# Generated by Django 2.2.16 on 2020-11-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_poll_multiple', '0004_auto_20201127_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livepollmultipleitemvote',
            name='vote_option',
        ),
    ]
