# Generated by Django 2.2.16 on 2020-12-08 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_poll_multiple', '0007_livepollmultiple_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepollmultipleitemvote',
            name='proxy_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multiple_proxy_user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livepollmultipleitemvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multiple_user_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
