# Generated by Django 2.2.16 on 2020-12-10 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_poll_multiple', '0008_auto_20201208_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepollmultipleproxy',
            name='live_poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multiple_live_poll_proxys', to='live_poll_multiple.LivePollMultiple'),
        ),
        migrations.AlterField(
            model_name='livepollmultipleproxy',
            name='main_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multiple_main_user_proxys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livepollmultipleproxy',
            name='proxy_users',
            field=models.ManyToManyField(related_name='multiple_proxy_users_proxys', to=settings.AUTH_USER_MODEL),
        ),
    ]
