# Generated by Django 2.2.16 on 2020-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_poll_multiple', '0010_auto_20201210_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepollmultipleitemvote',
            name='lots',
            field=models.SmallIntegerField(default=0, verbose_name='Number of Lots'),
        ),
    ]
