# Generated by Django 2.2.16 on 2020-11-24 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('title', models.CharField(max_length=255)),
                ('is_chosen', models.BooleanField(default=False, verbose_name='Is Chosen')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepoll_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepoll_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Live Poll',
                'verbose_name_plural': 'Live Polls',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivePollBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('batch_no', models.PositiveIntegerField(verbose_name='Batch No.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollbatch_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollbatch_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='live_poll.LivePoll')),
            ],
            options={
                'verbose_name': 'Live Poll Batch',
                'verbose_name_plural': 'Live Poll Batches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivePollItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sequence Order')),
                ('text', models.CharField(max_length=255)),
                ('is_open', models.BooleanField(default=False, verbose_name='Is Open')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Vote Opened At')),
                ('opening_duration_minustes', models.PositiveSmallIntegerField(default=5, verbose_name='Vote Opening Duration Minustes')),
                ('poll_type', models.PositiveSmallIntegerField(choices=[(1, 'By Share'), (2, 'By Lot')], default=1, verbose_name='Poll Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollitem_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollitem_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='live_poll.LivePoll')),
            ],
            options={
                'verbose_name': 'Live Poll Item',
                'verbose_name_plural': 'Live Poll Items',
                'ordering': ['order'],
                'managed': True,
                'unique_together': {('order', 'poll')},
            },
        ),
        migrations.CreateModel(
            name='LivePollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('result', jsonfield.fields.JSONField(blank=True, null=True)),
                ('voting_date', models.DateField(blank=True, null=True, verbose_name='Voting Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollresult_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('live_poll', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='live_poll.LivePollItem')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollresult_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Live Poll Result',
                'verbose_name_plural': 'Live Poll Results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivePollItemVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('vote_option', models.PositiveSmallIntegerField(verbose_name='Vote Option')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollitemvote_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollitemvote_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('poll_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_batches', to='live_poll.LivePollBatch')),
                ('poll_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_votes', to='live_poll.LivePollItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Poll Item Vote',
                'verbose_name_plural': 'Live Poll Item Votes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivePollProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollproxy_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_poll_livepollproxy_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('poll_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxy_batches', to='live_poll.LivePollBatch')),
                ('proxy_users', models.ManyToManyField(related_name='proxy_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Poll Proxy',
                'verbose_name_plural': 'Live Poll Proxys',
                'managed': True,
                'unique_together': {('poll_batch', 'main_user')},
            },
        ),
    ]
