# Generated by Django 2.2.16 on 2020-12-10 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepollitemvote',
            name='proxy_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxy_user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livepollitemvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
