# Generated by Django 2.2.16 on 2020-12-10 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_poll', '0002_auto_20201210_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepollresult',
            name='voting_date',
            field=models.DateField(auto_now=True, default=datetime.date(2020, 12, 10), verbose_name='Voting Date'),
            preserve_default=False,
        ),
    ]
