# Generated by Django 2.2.16 on 2020-12-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_poll', '0003_auto_20201210_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepollresult',
            name='live_poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='live_poll.LivePoll'),
        ),
    ]
