# Generated by Django 2.2.16 on 2020-12-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_poll', '0004_auto_20201210_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepollbatch',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchs', to='live_poll.LivePoll'),
        ),
        migrations.AlterField(
            model_name='livepollitemvote',
            name='poll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_votes', to='live_poll.LivePollBatch'),
        ),
        migrations.AlterField(
            model_name='livepollproxy',
            name='main_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_user_proxys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livepollproxy',
            name='poll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poll_batch_proxys', to='live_poll.LivePollBatch'),
        ),
        migrations.AlterField(
            model_name='livepollproxy',
            name='proxy_users',
            field=models.ManyToManyField(related_name='proxy_users_proxys', to=settings.AUTH_USER_MODEL),
        ),
    ]
