# Generated by Django 2.2.16 on 2020-12-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_poll', '0008_auto_20201217_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepollitem',
            name='text',
            field=models.TextField(max_length=1023),
        ),
    ]
