# Generated by Django 2.2.14 on 2020-07-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'managed': True, 'verbose_name': 'Company User', 'verbose_name_plural': 'Company Users'},
        ),
        migrations.AlterModelManagers(
            name='companyuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
