# Generated by Django 2.2.16 on 2020-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='block_no',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Block Number'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='unit_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Unit Number'),
        ),
    ]
