# Generated by Django 2.2.14 on 2020-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200711_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Vote Weighting'),
            preserve_default=False,
        ),
    ]
