# Generated by Django 2.2.14 on 2020-07-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200712_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Vote Weighting'),
        ),
    ]
