# Generated by Django 2.2.14 on 2020-07-17 23:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_companyuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='username',
            field=models.CharField(help_text='Required. 63 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=63, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
