# Generated by Django 2.2.16 on 2020-12-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201215_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True, 'ordering': ['company', 'user_type', 'username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='lot',
            order_with_respect_to='user',
        ),
    ]
