# Generated by Django 2.2.16 on 2020-12-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyvote',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='surveyvote',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='surveyoption',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_options', to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='surveyvote',
            name='survey_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_option_votes', to='survey.SurveyOption'),
        ),
        migrations.AlterField(
            model_name='surveyvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_user_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
