# Generated by Django 2.2.12 on 2020-08-12 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('title', models.CharField(max_length=255)),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('text', models.CharField(max_length=255)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ballot.Survey')),
            ],
            options={
                'verbose_name': 'Survey Option',
                'verbose_name_plural': 'Survey Options',
                'managed': True,
                'unique_together': {('text', 'survey')},
            },
        ),
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('survey_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ballot.SurveyOption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Vote',
                'verbose_name_plural': 'Survey Votes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('result', jsonfield.fields.JSONField(blank=True, null=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ballot.Survey')),
            ],
            options={
                'verbose_name': 'Survey Result',
                'verbose_name_plural': 'Survey Results',
                'managed': True,
            },
        ),
    ]
