# Generated by Django 2.2.12 on 2020-09-03 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('title', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepoll_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepoll_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Live Poll',
                'verbose_name_plural': 'Live Polls',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivePollItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sequence Order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollitem_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollitem_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ballot.LivePoll')),
            ],
            options={
                'verbose_name': 'Live Poll Item',
                'verbose_name_plural': 'Live Poll Items',
                'ordering': ['order'],
                'managed': True,
                'unique_together': {('text', 'poll')},
            },
        ),
    ]
