# Generated by Django 2.2.16 on 2020-11-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livepollbatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='livepollbatch',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='livepollbatch',
            name='poll',
        ),
        migrations.AlterUniqueTogether(
            name='livepollitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='livepollitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='livepollitem',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='livepollitem',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='livepollitemvote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='livepollitemvote',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='livepollitemvote',
            name='poll_batch',
        ),
        migrations.RemoveField(
            model_name='livepollitemvote',
            name='poll_item',
        ),
        migrations.RemoveField(
            model_name='livepollitemvote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='livepollproxy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='livepollproxy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='livepollproxy',
            name='main_user',
        ),
        migrations.RemoveField(
            model_name='livepollproxy',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='livepollproxy',
            name='poll_batch',
        ),
        migrations.RemoveField(
            model_name='livepollproxy',
            name='proxy_users',
        ),
        migrations.RemoveField(
            model_name='livepollresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='livepollresult',
            name='live_poll',
        ),
        migrations.RemoveField(
            model_name='livepollresult',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='LivePoll',
        ),
        migrations.DeleteModel(
            name='LivePollBatch',
        ),
        migrations.DeleteModel(
            name='LivePollItem',
        ),
        migrations.DeleteModel(
            name='LivePollItemVote',
        ),
        migrations.DeleteModel(
            name='LivePollProxy',
        ),
        migrations.DeleteModel(
            name='LivePollResult',
        ),
    ]
