# Generated by Django 2.2.16 on 2020-11-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_auto_20201124_0051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='surveyoption',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveyoption',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='surveyoption',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyvote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveyvote',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='surveyvote',
            name='survey_option',
        ),
        migrations.RemoveField(
            model_name='surveyvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyOption',
        ),
        migrations.DeleteModel(
            name='SurveyResult',
        ),
        migrations.DeleteModel(
            name='SurveyVote',
        ),
    ]
