# Generated by Django 2.2.12 on 2020-09-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_livepoll_livepollitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepoll',
            name='is_chosen',
            field=models.BooleanField(default=False, verbose_name='Is Chosen'),
        ),
    ]
