# Generated by Django 2.2.14 on 2020-08-12 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_survey_company_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'managed': True, 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterField(
            model_name='survey',
            name='company_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
