# Generated by Django 2.2.14 on 2020-08-12 01:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ballot', '0003_auto_20200812_0051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voting',
            new_name='SurveyVote',
        ),
        migrations.AlterModelOptions(
            name='surveyvote',
            options={'managed': True, 'verbose_name': 'Survey Vote', 'verbose_name_plural': 'Survey Votes'},
        ),
    ]
