# Generated by Django 2.2.14 on 2020-07-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0004_pollresult_voting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollresult',
            options={'managed': True, 'verbose_name': 'Poll Result', 'verbose_name_plural': 'Poll Results'},
        ),
    ]
