# Generated by Django 2.2.12 on 2020-09-04 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ballot', '0004_livepollitem_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePollItemVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('vote_option', models.PositiveSmallIntegerField(verbose_name='Vote Option')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollitemvote_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollitemvote_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('poll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_votes', to='ballot.LivePollItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Poll Item Vote',
                'verbose_name_plural': 'Live Poll Item Votes',
                'managed': True,
            },
        ),
    ]
