# Generated by Django 2.2.12 on 2020-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0005_livepollitemvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepollitem',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vote Opened At'),
        ),
        migrations.AddField(
            model_name='livepollitem',
            name='opening_duration_minustes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vote Opening Duration Minustes'),
        ),
    ]
