# Generated by Django 2.2.14 on 2020-10-07 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ballot', '0006_auto_20200904_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('result', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollresult_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('live_poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ballot.LivePoll')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollresult_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Live Poll Result',
                'verbose_name_plural': 'Live Poll Results',
                'managed': True,
            },
        ),
    ]
