# Generated by Django 2.2.14 on 2020-10-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0007_livepollresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepollresult',
            name='live_poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ballot.LivePollItem'),
        ),
    ]
