# Generated by Django 2.2.14 on 2020-10-07 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0008_auto_20201007_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepollresult',
            name='voting_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 7, 3, 8, 39, 113891), verbose_name='Voting Date'),
            preserve_default=False,
        ),
    ]
