# Generated by Django 2.2.14 on 2020-10-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0009_livepollresult_voting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepollitem',
            name='poll_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'By Share'), (2, 'By Lot')], null=True, verbose_name='Poll Type'),
        ),
    ]
