# Generated by Django 2.2.14 on 2020-10-14 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ballot', '0010_livepollitem_poll_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepollitem',
            name='poll_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'By Share'), (2, 'By Lot')], default=1, verbose_name='Poll Type'),
        ),
        migrations.CreateModel(
            name='LivePollProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollproxy_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollproxy_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('proxy_users', models.ManyToManyField(related_name='proxy_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Poll Proxy',
                'verbose_name_plural': 'Live Poll Proxys',
                'managed': True,
            },
        ),
    ]
