# Generated by Django 2.2.14 on 2020-10-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0011_auto_20201014_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepollitemvote',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='livepollitemvote',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent'),
        ),
    ]
