# Generated by Django 2.2.14 on 2020-10-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0012_auto_20201019_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepollresult',
            name='voting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Voting Date'),
        ),
    ]
