# Generated by Django 2.2.14 on 2020-10-19 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ballot', '0013_auto_20201019_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepoll',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Company'),
        ),
        migrations.AlterField(
            model_name='livepollitem',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ballot.LivePoll'),
        ),
        migrations.AlterField(
            model_name='livepollitemvote',
            name='poll_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_votes', to='ballot.LivePollItem'),
        ),
        migrations.AlterField(
            model_name='livepollitemvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livepollproxy',
            name='main_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='livepollresult',
            name='live_poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ballot.LivePollItem'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Company'),
        ),
        migrations.AlterField(
            model_name='surveyoption',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='ballot.Survey'),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ballot.Survey'),
        ),
        migrations.AlterField(
            model_name='surveyvote',
            name='survey_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='ballot.SurveyOption'),
        ),
        migrations.AlterField(
            model_name='surveyvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LivePollItemBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('vote_batch', models.PositiveIntegerField(verbose_name='Vote Batch No.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollitembatch_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollitembatch_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ballot.LivePoll')),
            ],
            options={
                'verbose_name': 'Live Poll Item Batch',
                'verbose_name_plural': 'Live Poll Item Batches',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='livepollitemvote',
            name='poll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_batches', to='ballot.LivePollItemBatch'),
        ),
    ]
