# Generated by Django 2.2.14 on 2020-10-19 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ballot', '0014_auto_20201019_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepollproxy',
            name='poll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxy_batches', to='ballot.LivePollItemBatch'),
        ),
        migrations.AlterField(
            model_name='livepollproxy',
            name='main_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='livepollproxy',
            unique_together={('poll_batch', 'main_user')},
        ),
    ]
