# Generated by Django 2.2.14 on 2020-10-19 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ballot', '0015_auto_20201019_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePollBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified At')),
                ('vote_batch', models.PositiveIntegerField(verbose_name='Vote Batch No.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollbatch_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_livepollbatch_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ballot.LivePoll')),
            ],
            options={
                'verbose_name': 'Live Poll Item Batch',
                'verbose_name_plural': 'Live Poll Item Batches',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='livepollitemvote',
            name='poll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_batches', to='ballot.LivePollBatch'),
        ),
        migrations.AlterField(
            model_name='livepollproxy',
            name='poll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxy_batches', to='ballot.LivePollBatch'),
        ),
        migrations.DeleteModel(
            name='LivePollItemBatch',
        ),
    ]
