# Generated by Django 2.2.14 on 2020-11-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0017_auto_20201019_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepollitem',
            name='opening_duration_minustes',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Vote Opening Duration Minustes'),
        ),
    ]
